[files]
extend-exclude = [
    "src/torch_structure_manipulation/structure_loader/bonding_data.json",
    "src/torch_structure_manipulation/structure_loader/load_structure_utils.py",   
    "src/torch_structure_manipulation/structure_transforms/utils.py",       
]
